# Generated by Django 5.0.7 on 2024-07-21 04:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(default='')),
                ('portrait', models.ImageField(blank=True, default='', null=True, upload_to='portraits/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cathegory', models.CharField(choices=[('N/A', 'N/A'), ('Suspenso', 'Suspenso'), ('Romance', 'Romance'), ('CienciaFiccion', 'Ciencia Ficción'), ('Aventura', 'Aventura'), ('Fantasía', 'Fantasía'), ('Acción', 'Acción')], default='N/A', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8, message='La contraseña debe tener al menos 8 caracteres')])),
                ('address', models.CharField(blank=True, default='No especificado', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payMethod', models.CharField(choices=[('Credit', 'Credit card'), ('Debit', 'Debit card'), ('Cash', 'Cash')], default='Credit', max_length=20)),
                ('total', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('idCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idCart_sale', to='bookstore.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='CartBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idBook_cartbook', to='bookstore.book')),
                ('idCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idCart_cartbook', to='bookstore.shoppingcart')),
            ],
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idUser_cart', to='bookstore.user'),
        ),
    ]
