# Generated by Django 5.0.7 on 2024-07-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='status',
        ),
    ]
