# Generated by Django 5.0.7 on 2024-07-21 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='idCart',
        ),
        migrations.AddField(
            model_name='sale',
            name='idBook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idBook_sale', to='bookstore.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='idUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idUser_sale', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
