# Generated by Django 5.0.7 on 2024-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, default='', null=True, upload_to='portraits/'),
        ),
    ]
