# Generated by Django 5.0.7 on 2024-07-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_shoppingcart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
